# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('word', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('paraphrase', models.TextField(max_length=100)),
                ('pronunciation', models.CharField(max_length=20)),
                ('subject', models.CharField(choices=[(1, '语文'), (2, '英语'), (3, '数学')], max_length=20)),
            ],
        ),
    ]
