# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='pronunciation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
