# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygame', '0002_auto_20171025_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.TextField(max_length=20, verbose_name='名称')),
                ('count', models.CharField(max_length=20, null=True, verbose_name='数量')),
                ('describe', models.CharField(max_length=100, verbose_name='描述')),
            ],
            options={
                'verbose_name': '道具',
                'verbose_name_plural': '道具',
            },
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'verbose_name': '词汇小怪', 'verbose_name_plural': '词汇小怪'},
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='paraphrase',
            field=models.TextField(max_length=100, verbose_name='意思'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='pronunciation',
            field=models.CharField(max_length=20, null=True, verbose_name='发音'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='subject',
            field=models.CharField(choices=[('001', '语文'), ('002', '英语'), ('003', '数学')], max_length=20, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='写法'),
        ),
    ]
