# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygame', '0005_auto_20171031_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='00', max_length=2, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.IntegerField(null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.IntegerField(verbose_name='赏金'),
        ),
    ]
