# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygame', '0007_accomplishedtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomplishedtask',
            old_name='task_id',
            new_name='task',
        ),
    ]
