# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygame', '0008_auto_20171102_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishedtask',
            name='desc',
            field=models.CharField(max_length=100, null=True, verbose_name='描述'),
        ),
    ]
