# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygame', '0010_auto_20171103_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('english_name', models.CharField(max_length=50, verbose_name='英文名')),
                ('chinese_name', models.CharField(max_length=10, verbose_name='中文名')),
                ('school_coin', models.IntegerField(verbose_name='斯古币')),
                ('english_ability', models.IntegerField(verbose_name='英语力')),
                ('chinese_ability', models.IntegerField(verbose_name='语言力')),
                ('math_ability', models.IntegerField(verbose_name='数学力')),
                ('drawing_ability', models.IntegerField(verbose_name='美术力')),
                ('music_ability', models.IntegerField(verbose_name='音乐力')),
                ('labour_ability', models.IntegerField(verbose_name='劳动力')),
                ('physique_ability', models.IntegerField(verbose_name='身体力')),
                ('memory', models.IntegerField(verbose_name='记忆力')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField(default=0, verbose_name='数学力')),
                ('math', models.IntegerField(default=0, verbose_name='数学力')),
                ('drawing', models.IntegerField(default=0, verbose_name='美术力')),
                ('physique', models.IntegerField(default=0, verbose_name='身体力')),
                ('chinese', models.IntegerField(default=0, verbose_name='语文力')),
                ('labour', models.IntegerField(default=0, verbose_name='劳动力')),
                ('music', models.IntegerField(default=0, verbose_name='音乐力')),
                ('memory', models.IntegerField(default=0, verbose_name='记忆力')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygame.Task')),
            ],
        ),
    ]
