# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygame', '0011_player_taskability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskability',
            old_name='task_id',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='player',
            name='chinese_ability',
            field=models.IntegerField(verbose_name='语文力'),
        ),
    ]
