# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygame', '0014_vocabulary_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='subject',
            field=models.CharField(choices=[('001', '语文'), ('002', '英语'), ('003', '数学'), ('301', '美术'), ('302', '音乐'), ('301', '体育'), ('601', '记忆'), ('602', '劳动')], max_length=4, null=True, verbose_name='科目'),
        ),
    ]
