# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygame', '0017_auto_20171106_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('sentence', models.CharField(max_length=500, verbose_name='句子')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygame.Vocabulary')),
            ],
        ),
        migrations.AlterModelOptions(
            name='taskitem',
            options={'verbose_name': '任务道具', 'verbose_name_plural': '任务道具'},
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='url'),
        ),
    ]
