# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygame', '0018_auto_20171107_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskability',
            options={'verbose_name': '任务能力成长', 'verbose_name_plural': '任务能力成长'},
        ),
        migrations.AlterField(
            model_name='taskability',
            name='english',
            field=models.IntegerField(default=0, verbose_name='英语力'),
        ),
    ]
