# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygame', '0019_auto_20171107_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayGrowUpDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField(default=0, verbose_name='英语力')),
                ('math', models.IntegerField(default=0, verbose_name='数学力')),
                ('drawing', models.IntegerField(default=0, verbose_name='美术力')),
                ('physique', models.IntegerField(default=0, verbose_name='身体力')),
                ('chinese', models.IntegerField(default=0, verbose_name='语文力')),
                ('labour', models.IntegerField(default=0, verbose_name='劳动力')),
                ('music', models.IntegerField(default=0, verbose_name='音乐力')),
                ('memory', models.IntegerField(default=0, verbose_name='记忆力')),
                ('school_coin', models.IntegerField(verbose_name='斯古币')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='完成时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygame.Task')),
            ],
        ),
    ]
